// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://esdhiurlyicjopjlxvba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZGhpdXJseWljam9wamx4dmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NjMwNTEsImV4cCI6MjA4ODIzOTA1MX0.zyUR-ymc1c3OlEDNozUdAnT7OxKi46M1qx0JJN0gvAM";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);